const mockData = [
  {
    worker_id: 1,
    first_name: "Dale",
    last_name: "Reynolds",
    rating: 4.8,
    rate: 24,
    years_exp: 10,
    description: "Very experienced electrician with a wide range of skills.",
    photo: "path_to_electrician_photo", // Replace with actual path or base64 image
    skills: ["communication", "patience", "knowledgeable"],
    trade: "Electrical",
    phone: "7766054665",
    email: "dale@example.com",
  },
  {
    worker_id: 2,
    first_name: "Susan",
    last_name: "Harper",
    rating: 4.5,
    rate: 30,
    years_exp: 8,
    description: "Skilled plumber who can handle complex systems.",
    photo: "path_to_plumber_photo",
    skills: ["problem-solving", "detail-oriented", "punctual"],
    trade: "Plumbing",
    phone: "7766054777",
    email: "susan@example.com",
  },
  {
    worker_id: 3,
    first_name: "Mike",
    last_name: "Johnson",
    rating: 4.6,
    rate: 22,
    years_exp: 5,
    description:
      "Dedicated lawning specialist with a passion for green spaces.",
    photo: "path_to_lawning_photo",
    skills: ["creative", "hardworking", "plant knowledge"],
    trade: "Lawning",
    phone: "7766054888",
    email: "mike@example.com",
  },
  {
    worker_id: 4,
    first_name: "Angela",
    last_name: "Martinez",
    rating: 4.9,
    rate: 35,
    years_exp: 12,
    description: "Master carpenter with award-winning designs.",
    photo: "path_to_carpentry_photo",
    skills: ["precision", "artistic", "technical skill"],
    trade: "Carpentry",
    phone: "7766054999",
    email: "angela@example.com",
  },
  {
    worker_id: 5,
    first_name: "Richard",
    last_name: "Smith",
    rating: 4.7,
    rate: 25,
    years_exp: 7,
    description: "Insurance expert with a knack for finding the best deals.",
    photo: "path_to_insurance_photo",
    skills: ["analytical", "trustworthy", "client-focused"],
    trade: "Insurance",
    phone: "7766054000",
    email: "richard@example.com",
  },
  {
    worker_id: 6,
    first_name: "Jessica",
    last_name: "Brown",
    rating: 4.4,
    rate: 20,
    years_exp: 6,
    description: "Creative painter with a great eye for color combinations.",
    photo: "path_to_painting_photo",
    skills: ["artistic", "meticulous", "efficient"],
    trade: "Painting",
    phone: "7766054111",
    email: "jessica@example.com",
  },
  // Additional workers to reach 10, with trades repeated
  {
    worker_id: 7,
    first_name: "Lucas",
    last_name: "Garcia",
    rating: 4.7,
    rate: 28,
    years_exp: 9,
    description: "Innovative electrician focused on sustainable solutions.",
    photo: "path_to_electrician_photo_2",
    skills: ["innovative", "eco-friendly", "experienced"],
    trade: "Electrical",
    phone: "7766054222",
    email: "lucas@example.com",
  },
  {
    worker_id: 8,
    first_name: "Emily",
    last_name: "Wilson",
    rating: 4.3,
    rate: 27,
    years_exp: 4,
    description: "Enthusiastic plumber who thrives on fixing the unfixable.",
    photo: "path_to_plumber_photo_2",
    skills: ["enthusiastic", "resilient", "problem-solver"],
    trade: "Plumbing",
    phone: "7766054333",
    email: "emily@example.com",
  },
];

export default mockData;
